- hosts: terraform-ansible
  tasks:
    - name: instalando python3 e virtualenv
      apt:
        pkg:
          - python3
          - virtualenv
        update_cache: yes
      become: yes
    - name: instalando dependencias com pip3(Django e Django Rest)
      pip:
        virtualenv: /home/ubuntu/projeto/venv
        name:
          - django
          - djangorestframework
    - name: iniciando projeto
      shell: '. /home/ubuntu/projeto/venv/bin/activate; django-admin startproject setup /home/ubuntu/projeto/'          
      